### ISSUE TITLE
Getting

### ISSUE THREAD

**Issue by agomez314** [escaladesports/amazon-reviews-crawler#1]
Hi. I'd like to understand which URL is being used to pull the reviews from. When I run the example, I get a seemingly random assortment of reviews, many of which are not displayed either in the homepage or reviews list. 

Also, is there a way to crawl through all different review pages? Thanks.

**Comment by kennedyrose** [comment]
I've fixed the crawler to pull most recent reviews from all reviewers on the first page. At the moment, there is no way to pull past reviews. This may be added at some point. Thanks!
